### ISSUE TITLE
Needs 'name' field

### ISSUE THREAD

**Issue by Marxsal** [EvidentlyCube/TW5-GoToShortcut#1]
The 'name' field is missing. This is used by some plugin management tools, esp. _External JS_

**Comment by EvidentlyCube** [comment]
I am going to assume it's missing in `plugin.info` in which case it's missing in all of my plugins - I'll sort it out soon.

**Comment by EvidentlyCube** [comment]
@Marxsal `name` field is now available in every plugin.
