### ISSUE TITLE
Why not use ctrl+p to open search?

### ISSUE THREAD

**Issue by linonetwo** [EvidentlyCube/TW5-GoToShortcut#2]
Or I think we can share a similar tm-message to open the command palette, like `open-command-palette`

```
key: ((open-command-palette))
tags: $:/tags/KeyboardShortcut
title: $:/core/ui/KeyboardShortcuts/CommandPalette
type: text/vnd.tiddlywiki

<$action-sendmessage $message="open-command-palette"/>
```

**Comment by linonetwo** [comment]
To increase Interoperability

**Comment by EvidentlyCube** [comment]
Supporting a message is a nice idea, I'll add it to my roadmap notes.

Other than that the keyboard shortcut is customizable in **Control Panel** -> **Keyboard Shortcut** -> **EC-GoToModal**. Just checked that it works in the latest version.

Ctrl+P would overwrite the native browser's print shortcut which isn't very user friendly so I'm against changing the default.

I am closing this as the keyboard shortcut customization is possible.

**Comment by linonetwo** [comment]
Ok, just because my TidGi have a native button to trigger command palette using message, so I suggest we use the same message so user can switch between command palette solutions freely.

**Comment by EvidentlyCube** [comment]
I'd rather not use the same widget message in case someone wants to use both solution simultaneously for some reason.

But how about this: if I add a support for reacting to messages I'll make it such that there is an option (disabled by default) to also react to command palette's message?

**Comment by linonetwo** [comment]
Though I don't think someone will install two command palette, but what you supposed is ok.

**Comment by linonetwo** [comment]
These plugins should be replacements for each other. I may create another plugin using [https://github.com/pacocoursey/cmdk](https://github.com/pacocoursey/cmdk) , it will be larger (requires ReactJS plugin) but being more powerful.

**Comment by EvidentlyCube** [comment]
> Though I don't think someone will install two command palette,

It is unlikely but I also learned the hard way many times in my career that users come up with scenarios the developer can't imagine. I'd rather stay flexible.
